services:
  node:
    build:
      context: ./docker
    volumes:
      - ./:/srv/app:rw,cached
    env_file:
      - .env
    labels:
      - word.enable=true
    command: ["bun", "--watch", "run", "src/main.ts"]