version: '3.8'

services:
  discord:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/srv/bot
      - .:/node_module
    restart: always

volumes:
  node_modules:
