version: '3.8'

services:
  discord:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - api-luluchan_nesjs-network
    volumes:
      - .:/srv/bot
      - .:/node_module
    restart: always

volumes:
  node_modules:

networks:
  api-luluchan_nesjs-network:
  default:
    external:
      name: bot-luluchan